@tool
class_name LivePaletteData
extends Resource

const META := &"_live_palette_bindings"

## [{id: String, name: String, color: Color}]
@export var entries: Array[Dictionary] = []


func find_index(p_id: String) -> int:
	for i in entries.size():
		if entries[i]["id"] == p_id:
			return i
	return -1


func get_color_by_id(p_id: String) -> Color:
	var i := find_index(p_id)
	if i < 0:
		return Color.WHITE
	return entries[i]["color"]


func get_color_by_name(p_name: StringName) -> Color:
	for e in entries:
		if e["name"] == String(p_name):
			return e["color"]
	push_warning("LivePalette: no color named '%s'" % p_name)
	return Color.WHITE


func has_color_name(p_name: StringName) -> bool:
	for e in entries:
		if e["name"] == String(p_name):
			return true
	return false


func new_id() -> String:
	var id := generate_scene_unique_id()
	while find_index(id) >= 0:
		id = generate_scene_unique_id()
	return id


# -- mutators: the sole write path; each emits changed --

func add_entry(p_id: String, p_name: String, p_color: Color, p_index: int = -1) -> void:
	var e := {"id": p_id, "name": p_name, "color": p_color}
	if p_index < 0 or p_index >= entries.size():
		entries.append(e)
	else:
		entries.insert(p_index, e)
	emit_changed()


func remove_entry(p_id: String) -> void:
	var i := find_index(p_id)
	if i >= 0:
		entries.remove_at(i)
		emit_changed()


func rename_entry(p_id: String, p_name: String) -> void:
	var i := find_index(p_id)
	if i >= 0:
		entries[i]["name"] = p_name
		emit_changed()


## p_to_index is the entry's index in the resulting array, so undo is move_entry(id, old_index).
func move_entry(p_id: String, p_to_index: int) -> void:
	var i := find_index(p_id)
	if i < 0:
		return
	var e: Dictionary = entries[i]
	entries.remove_at(i)
	entries.insert(clampi(p_to_index, 0, entries.size()), e)
	emit_changed()


func set_color(p_id: String, p_color: Color) -> void:
	var i := find_index(p_id)
	if i >= 0:
		entries[i]["color"] = p_color
		emit_changed()


# -- constants script generation (text only; the plugin writes the file) --

## "Sky Blue" -> "SKY_BLUE". Returns "" when nothing usable is left.
static func const_identifier(p_name: String) -> String:
	var out := ""
	for c in p_name.to_upper():
		out += c if (c >= "A" and c <= "Z") or (c >= "0" and c <= "9") else "_"
	while out.contains("__"):
		out = out.replace("__", "_")
	out = out.lstrip("_").rstrip("_")
	if out.is_empty():
		return ""
	if out[0] >= "0" and out[0] <= "9":
		out = "C_" + out  # identifiers can't start with a digit
	return out


## %s slots: source path, class name, consts, class name, lookup pairs, class name.
const CONST_TEMPLATE := """# Generated by the Live Palette addon from %s.
# Do not edit — it is rewritten whenever the palette changes.
class_name %s

%s

## Palette name -> color, for lookups by a name held in a variable.
## Prefer the constants above: %s.MY_COLOR is checked at compile time.
const BY_NAME := {
%s
}


static func color(p_name: StringName) -> Color:
	var key := str(p_name)
	if BY_NAME.has(key):
		return BY_NAME[key]
	push_warning("%s: no color named '%%s'" %% p_name)
	return Color.WHITE


static func has_color(p_name: StringName) -> bool:
	return BY_NAME.has(str(p_name))
"""


## GDScript source exposing every entry as a Color constant, for autocompleted access.
func build_const_script(p_class_name: String, p_source_path: String) -> String:
	var consts := PackedStringArray()
	var pairs := PackedStringArray()
	var used := {}
	for e in entries:
		var ident := const_identifier(str(e["name"]))
		if ident.is_empty():
			ident = "C_" + str(e["id"]).to_upper()
		var base := ident
		var n := 2
		while used.has(ident):  # two names can sanitize to the same identifier
			ident = "%s_%d" % [base, n]
			n += 1
		used[ident] = true
		consts.append("const %s := %s" % [ident, var_to_str(e["color"])])
		pairs.append("\t%s: %s," % [var_to_str(str(e["name"])), ident])
	return CONST_TEMPLATE % [
		p_source_path, p_class_name, "\n".join(consts), p_class_name, "\n".join(pairs), p_class_name,
	]


# -- GIMP .gpl import/export (the palette format Lospec, Aseprite and Krita speak) --

## Parses .gpl text into [{name: String, color: Color}]. Unparseable lines are skipped.
static func parse_gpl(p_text: String) -> Array[Dictionary]:
	var out: Array[Dictionary] = []
	var rgba := false
	for raw in p_text.split("\n"):
		var line := raw.strip_edges()
		if line.is_empty() or line.begins_with("#"):
			continue
		var lower := line.to_lower()
		if lower.begins_with("gimp palette") or lower.begins_with("name:") or lower.begins_with("columns:"):
			continue
		if lower.begins_with("channels:"):  # Krita writes "Channels: RGBA" for 4-value lines
			rgba = lower.contains("rgba")
			continue
		var tokens := line.replace("\t", " ").split(" ", false)
		var want := 4 if rgba else 3
		if tokens.size() < want:
			continue
		var numeric := true
		for i in want:
			if not tokens[i].is_valid_int():
				numeric = false
				break
		if not numeric:
			continue
		var a := clampi(tokens[3].to_int(), 0, 255) if rgba else 255
		var c := Color8(clampi(tokens[0].to_int(), 0, 255), clampi(tokens[1].to_int(), 0, 255), clampi(tokens[2].to_int(), 0, 255), a)
		out.append({"name": " ".join(tokens.slice(want)), "color": c})
	return out


## The format is RGB: alpha is flattened on export.
func to_gpl(p_palette_name: String) -> String:
	var lines := PackedStringArray(["GIMP Palette", "Name: %s" % p_palette_name, "Columns: 8", "#"])
	for e in entries:
		var c: Color = e["color"]
		lines.append("%d %d %d\t%s" % [c.r8, c.g8, c.b8, e["name"]])
	return "\n".join(lines) + "\n"


# -- uses scan --

## Counts references to p_id inside _live_palette_bindings blocks of a .tscn/.tres text.
## Ignores the id appearing anywhere else in the file.
static func find_uses_in_text(p_text: String, p_id: String) -> int:
	var needle := "\"%s\"" % p_id
	var n := 0
	var from := p_text.find(String(META))
	while from >= 0:
		var close := p_text.find("}", from)  # binding dict holds only strings: first } closes it
		if close < 0:
			close = p_text.length()
		n += p_text.substr(from, close - from).count(needle)
		from = p_text.find(String(META), close + 1)
	return n


static func hex(p_color: Color) -> String:
	return "#" + p_color.to_html(p_color.a < 1.0).to_upper()


func apply_to_tree(p_root: Node) -> int:
	return _apply_recursive(p_root, {})


func _apply_recursive(p_node: Node, p_visited: Dictionary) -> int:
	var n := apply_to_object(p_node, p_visited)
	for c in p_node.get_children():
		n += _apply_recursive(c, p_visited)
	return n


func apply_to_object(p_obj: Object, p_visited: Dictionary) -> int:
	var iid := p_obj.get_instance_id()
	if p_visited.has(iid):
		return 0
	p_visited[iid] = true
	var n := 0
	if p_obj.has_meta(META):
		var bindings: Dictionary = p_obj.get_meta(META)
		for prop in bindings:
			var i := find_index(str(bindings[prop]))
			if i < 0:
				continue
			var c: Color = entries[i]["color"]
			var cur: Variant = p_obj.get(prop)
			if cur is Color and not cur.is_equal_approx(c):
				p_obj.set(prop, c)
				n += 1
	for p in p_obj.get_property_list():
		if p["type"] == TYPE_OBJECT and (p["usage"] & PROPERTY_USAGE_STORAGE) and p["name"] != "script":
			var v: Variant = p_obj.get(p["name"])
			if v is Resource:
				n += apply_to_object(v, p_visited)
	return n
